<?php

function universal_bar_menu(){
  $items = array();

  $items['admin/config/system/universal_bar'] = array(
    'title' => 'Universal Bar',
    'description' => 'Configuration for Universal Bar settings',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('universal_bar_form'),
    'access arguments' => array('access administration pages'),
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

function universal_bar_form($form, &$form_state) {
  $form['universal_bar_name'] = array(
    '#type' => 'textfield',
    '#title' => t('Universal Bar Name'),
    '#default_value' => variable_get('universal_bar_name'),
    '#description' => t('The name of the entity to display on the universal bar.'),
  );

  $form['universal_bar_sites'] = array(
    '#type' => 'textarea',
    '#title' => t('Universal Bar Sites List'),
    '#default_value' => variable_get('universal_bar_sites'),
    '#description' => t('HTML content of the sites list.'),
    'format'=> filter_default_format(),
  );

  return system_settings_form($form);
}

function curPageURL() {
 $pageURL = 'http';
 if (isset($_SERVER["HTTPS"]) && $_SERVER["HTTPS"]== "on") {$pageURL .= "s";}
 $pageURL .= "://";
 if ($_SERVER["SERVER_PORT"] != "80") {
  $pageURL .= $_SERVER["SERVER_NAME"].":".$_SERVER["SERVER_PORT"].$_SERVER["REQUEST_URI"];
 } else {
  $pageURL .= $_SERVER["SERVER_NAME"].$_SERVER["REQUEST_URI"];
 }
 return $pageURL;
}
function universal_bar_page_alter(&$page){
	$mod_path="/".drupal_get_path('module', 'universal_bar');

	$account_in_out;
	$account_user="";
	$feedback_ref=urlencode(curPageURL());
	if(user_is_logged_in()){
		$account_user='<a href="https://forgoodaccounts.pairsite.com/user"><i class="fa fa-user"></i><span class="show-for-medium-up">Account</span></a>';
		$account_in_out='<a href="/caslogout"><i class="fa fa-sign-out"></i><span class="show-for-medium-up">Sign Out</span></a>';
	}else{
		$account_user='<a class="button small" href="https://forgoodaccounts.pairsite.com/user/register"><i class="fa fa-plus"></i><i class="fa fa-user"></i><span class="show-for-medium-up">Create Account/span></a>';
		$account_in_out='<a href="/cas/login"><i class="fa fa-sign-in"></i><span class="show-for-medium-up">Sign In</span></a>';
	}
	$sites_list='
	<div class="display-panel">
		<ul class="sites-list small-block-grid-3 menu">
			<li>
        <a title="Forgood Studios" href="http://forgoodstudios.org">
          <img src="'.$mod_path.'/images/studios.png" alt="Forgood Studios" />
          <span>Forgood Studios</span>
        </a>
      </li>
			<li>
        <a title="Housing" href="http://forgoodhousing.org">
          <img src="'.$mod_path.'/images/housing.png" alt="Forgood Housing" />
          <span>Housing</span>
        </a>
      </li>
			<li>
        <a title="Forgood Ideas" href="http://reddit.com/r/forgoodideas">
          <img src="'.$mod_path.'/images/ideas.png" alt="Forgood Ideas" />
          <span>Ideas</span>
        </a>
      </li>
			<li>
        <a title="Forgood Accounts" href="http://forgoodaccounts.pairsite.com">
          <img src="'.$mod_path.'/images/accounts.png" alt="Forgood Accounts" />
          <span>Accounts</span>
        </a>
      </li>
			<li>
        <a title="Redjacket Arts" href="http://redjacketarts.com">
          <img src="'.$mod_path.'/images/redjacket.png" alt="Redjacket Arts" />
          <span>Redjacket Arts</span>
        </a>
      </li>
		</ul>
		<div class="display-panel-footer">
			<a href="https://forgoodaccounts.pairsite.com/site-descriptions">Site Descriptions</a>
		</div>
	</div>';
	$notifications=
	'<div class="display-panel">
	<div id="notifications"></div>
	<div class="display-panel-footer">
		<a href="https://forgoodaccounts.pairsite.com/notifications">Notifications Manager</a>
	</div>
	</div>';
    $page['page_top']['universal_bar']=array(
    '#markup'=>
    '<div class="universal-bar">
		<div class="row">
		  <div class="left">
			<ul class="title-area">
			  <li class="name">
			    <a href="/" rel="home"><img class="logo" src="'.$mod_path.'/images/forgood.png" alt="Forgood Studios"></a>
			  </li>
			</ul>
		  </div>
			<div class="right">
				<ul class="menu inline-list">
					<li>'.$account_user.'</li>
					<li id="toggle-sites-list"><a title="Sites"><i class="fa fa-th"><span class="show-for-large-up">Sites</span></i></a>
						'.$sites_list.'
					</li>
					<!--li id="toggle-notifications"><a title="Notifications"><i class="fa fa-bell"><span class="show-for-medium-up">Notifications</span></i><span class="notif-count"></span></a>
						'.$notifications.'
					</li-->
					<li><a href="https://forgoodaccounts.pairsite.com/feedback?ref='.$feedback_ref.'" title="Feedback"><i class="fa fa-question-circle"><span class="show-for-medium-up">Feedback</span></i></a>
						'.$notifications.'
					</li>
					<li>'.$account_in_out.'</li>
				</ul>
			</div>
		</div>
    </div>',
    '#weight' => 26,
    );

}
