<?php

function universal_bar_menu(){
  $items = array();

  $items['admin/config/system/universal_bar'] = array(
    'title' => 'Universal Bar',
    'description' => 'Configuration for Universal Bar settings',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('universal_bar_form'),
    'access arguments' => array('access administration pages'),
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

function universal_bar_form($form, &$form_state) {
  $form['universal_bar_name'] = array(
    '#type' => 'textfield',
    '#title' => t('Universal Bar Name'),
    '#default_value' => variable_get('universal_bar_name'),
    '#description' => t('The name of the entity to display on the universal bar.'),
  );

  $form['universal_bar_sites'] = array(
    '#type' => 'textarea',
    '#title' => t('Universal Bar Sites List'),
    '#default_value' => variable_get('universal_bar_sites'),
    '#description' => t('HTML content of the sites list.'),
    'format'=> filter_default_format(),
  );

  return system_settings_form($form);
}

function curPageURL() {
 $pageURL = 'http';
 if (isset($_SERVER["HTTPS"]) && $_SERVER["HTTPS"]== "on") {$pageURL .= "s";}
 $pageURL .= "://";
 $pageURL .= $_SERVER["SERVER_NAME"].$_SERVER["REQUEST_URI"];
 return $pageURL;
}
function universal_bar_page_alter(&$page){
	$mod_path="/".drupal_get_path('module', 'universal_bar');
	$site_domain=check_plain($_SERVER['HTTP_HOST']);
	$embed="?response_type=embed";
	$feedback_source="https://accounts.forgood.io/feedback";
	$feedback_ref=urlencode(curPageURL());
	if (user_is_logged_in()){
		$account='<a href="https://accounts.forgood.io/user" data-reveal-id="account_user-reveal-drawer"><i class="fa fa-user"></i><span class="show-for-medium-up">Account</span></a>
		<div id="account_user-reveal-drawer" class="reveal-modal side-drawer" data-reveal>
		  <iframe class="fill-drawer" src="https://accounts.forgood.io/user?response_type=embed"></iframe>
			<div class="action-panel">
			  <a class="close-reveal-modal"><i class="fa fa-close"></i></a>
			  <a target="_blank" href="https://accounts.forgood.io/user"><i class="fa fa-external-link"></i></a>
			</div>
		</div>';
	} else {
		$destination = drupal_get_destination();
		$destination = $destination['destination'];
		$account='<a class="login-button" href="/cas?destination='.$destination.'"><i class="fa fa-user"></i><span class="show-for-medium-up">Log In</span></a>';
	}
	$sites_list='
	<div id="sites-reveal-drawer" class="reveal-modal side-drawer" data-reveal>
		<ul class="sites-list small-block-grid-1 menu">
		  <li>
			<a title="Forgood Studios" href="https://forgood.io">
			  <img src="'.$mod_path.'/images/studios.png" alt="Forgood Studios" />
			</a>
		  </li>
		  <li>
			<a title="Housing" href="https://housing.forgood.io">
			  <img src="'.$mod_path.'/images/housing.png" alt="Forgood Housing" />
			</a>
		  </li>
		  <li>
			<a title="Forgood Accounts" href="https://accounts.forgood.io">
			  <img src="'.$mod_path.'/images/accounts.png" alt="Forgood Accounts" />
			</a>
		  </li>
		</ul>
		<div class="action-panel">
		  <a class="close-reveal-modal"><i class="fa fa-close"></i></a>
		  <a target="_blank" href="https://accounts.forgood.io/site-descriptions"><i class="fa fa-external-link"></i></a>
		</div>
	</div>';
  $feedback='
  <div id="feedback-reveal-drawer" class="reveal-modal side-drawer" data-reveal>
    <iframe class="fill-drawer" src="'.$feedback_source.$embed.'&ref='.$feedback_ref.'"></iframe>
    <div class="action-panel">
      <a class="close-reveal-modal"><i class="fa fa-close"></i></a>
      <a target="_blank" href="'.$feedback_source.'"><i class="fa fa-external-link"></i></a>
    </div>
  </div>
  ';
    $page['page_top']['universal_bar']=array(
    '#markup'=>
    '<div class="universal-bar">
		<div class="row">
		  <div class="left">
			<ul class="title-area">
			  <li class="name">
			    <a href="/" rel="home"><img class="logo" src="'.$mod_path.'/images/forgood.png" alt="Forgood Studios"></a>
			  </li>
			</ul>
		  </div>
			<div class="right">
				<ul class="menu inline-list">
					<li><a title="Sites" href="#" data-reveal-id="sites-reveal-drawer"><i class="fa fa-th"></i><span class="show-for-medium-up">Sites</span></a>
						'.$sites_list.'
					</li>
					<li><a href="https://accounts.forgood.io/feedback" title="Feedback" data-reveal-id="feedback-reveal-drawer"><i class="fa fa-question-circle"></i><span class="show-for-medium-up">Feedback</span></a>'.$feedback.'
					</li>
					<li>'.$account.'</li>
				</ul>
			</div>
		</div>
    </div>',
    '#weight' => 26,
    );

}
